/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orange_documentare_core_comp_bwt_SaisBwt */

#ifndef _Included_com_orange_documentare_core_comp_bwt_SaisBwt
#define _Included_com_orange_documentare_core_comp_bwt_SaisBwt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orange_documentare_core_comp_bwt_SaisBwt
 * Method:    getBwtNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_orange_documentare_core_comp_bwt_SaisBwt_getBwtNative
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
