Document: simdoc-server
Title: Debian simdoc-server Manual
Author: <insert document author here>
Abstract: This manual describes what simdoc-server is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/simdoc-server/simdoc-server.sgml.gz

Format: postscript
Files: /usr/share/doc/simdoc-server/simdoc-server.ps.gz

Format: text
Files: /usr/share/doc/simdoc-server/simdoc-server.text.gz

Format: HTML
Index: /usr/share/doc/simdoc-server/html/index.html
Files: /usr/share/doc/simdoc-server/html/*.html
